// Port of lib/core/utils/category_icons.dart. GENERATED — edit the Dart map
// first, then regenerate; hand-edits here will drift.
//
// The stored value is the KEY on the left; the phone maps it to a Flutter
// icon. Here it maps to the Material Symbols ligature of the same glyph, so
// both ends show the same picture. Keys must stay identical to the Dart map —
// a key this app invents would render as the fallback glyph on the phone.

export const ICON_GROUPS = [
  {
    label: 'General',
    icons: {
      category: 'category',
      other: 'more_horiz',
      star: 'star',
      tag: 'sell',
      flag: 'flag',
      bookmark: 'bookmark',
    },
  },
  {
    label: 'Food & drink',
    icons: {
      groceries: 'local_grocery_store',
      restaurant: 'restaurant',
      coffee: 'local_cafe',
      fastfood: 'fastfood',
      bakery: 'bakery_dining',
      liquor: 'local_bar',
      icecream: 'icecream',
      lunch: 'lunch_dining',
      dinner: 'dinner_dining',
      breakfast: 'breakfast_dining',
      noodles: 'ramen_dining',
      pizza: 'local_pizza',
      rice: 'rice_bowl',
      egg: 'egg',
      seafood: 'set_meal',
      wine: 'wine_bar',
      juice: 'local_drink',
      takeaway: 'takeout_dining',
      delivery: 'delivery_dining',
      dining: 'dining',
      candy: 'cake',
    },
  },
  {
    label: 'Home & living',
    icons: {
      home: 'home',
      cleaning: 'cleaning_services',
      bed: 'bed',
      chair: 'chair',
      kitchen: 'kitchen',
      lightbulb: 'lightbulb',
      tools: 'handyman',
      yard: 'yard',
      apartment: 'apartment',
      house: 'house',
      rent: 'real_estate_agent',
      furniture: 'weekend',
      laundry: 'local_laundry_service',
      shower: 'shower',
      bath: 'bathtub',
      door: 'door_front',
      window: 'window',
      roof: 'roofing',
      plumbing: 'plumbing',
      electrical: 'electrical_services',
      carpenter: 'carpenter',
      paint: 'format_paint',
      construction: 'construction',
      repair: 'home_repair_service',
      aircon: 'ac_unit',
      fan: 'mode_fan_off',
      heater: 'local_fire_department',
      security: 'security',
    },
  },
  {
    label: 'Bills & utilities',
    icons: {
      bills: 'receipt_long',
      utilities: 'bolt',
      water: 'water_drop',
      gas: 'local_fire_department',
      internet: 'wifi',
      phone: 'phone_iphone',
      tv: 'tv',
      receipt: 'receipt',
      payment: 'payment',
      invoice: 'request_quote',
      exchange: 'currency_exchange',
      loan: 'account_balance_wallet',
      debt: 'money_off',
      cash: 'attach_money',
      wallet: 'wallet',
      calculator: 'calculate',
      chart: 'bar_chart',
      solar: 'solar_power',
      power: 'power',
      router: 'router',
      simcard: 'sim_card',
      cable: 'cable',
    },
  },
  {
    label: 'Transport',
    icons: {
      transport: 'directions_car',
      fuel: 'local_gas_station',
      parking: 'local_parking',
      bus: 'directions_bus',
      train: 'train',
      taxi: 'local_taxi',
      bike: 'pedal_bike',
      motorcycle: 'two_wheeler',
      flight: 'flight',
      travel: 'luggage',
      walk: 'directions_walk',
      boat: 'directions_boat',
      ferry: 'sailing',
      ev: 'electric_car',
      charging: 'ev_station',
      rental: 'car_rental',
      wash: 'local_car_wash',
      delivery_truck: 'local_shipping',
      scooter: 'moped',
      subway: 'subway',
      tram: 'tram',
      toll: 'toll',
      traffic: 'traffic',
    },
  },
  {
    label: 'Shopping',
    icons: {
      shopping: 'shopping_bag',
      clothing: 'checkroom',
      electronics: 'devices',
      beauty: 'spa',
      gift: 'card_giftcard',
      jewelry: 'diamond',
      store: 'storefront',
      mall: 'local_mall',
      cart: 'shopping_cart',
      basket: 'shopping_basket',
      offer: 'local_offer',
      loyalty: 'loyalty',
      shoes: 'ice_skating',
      watch: 'watch',
    },
  },
  {
    label: 'Health',
    icons: {
      health: 'local_hospital',
      pharmacy: 'medication',
      fitness: 'fitness_center',
      dental: 'medical_services',
      vaccine: 'vaccines',
      healing: 'healing',
      heart: 'monitor_heart',
      mental: 'psychology',
      eye: 'visibility',
      wellness: 'self_improvement',
      blood: 'bloodtype',
      emergency: 'emergency',
      sick: 'sick',
      mask: 'masks',
    },
  },
  {
    label: 'Family & people',
    icons: {
      kids: 'child_care',
      pet: 'pets',
      school: 'school',
      education: 'menu_book',
      family: 'family_restroom',
      baby: 'baby_changing_station',
      stroller: 'stroller',
      birthday: 'cake',
      elderly: 'elderly',
      community: 'diversity_3',
      charity: 'volunteer_activism',
      favourite: 'favorite',
      group: 'groups',
      wedding: 'celebration',
    },
  },
  {
    label: 'Leisure',
    icons: {
      entertainment: 'movie',
      music: 'music_note',
      games: 'sports_esports',
      sports: 'sports_soccer',
      hobby: 'palette',
      book: 'auto_stories',
      cinema: 'theaters',
      basketball: 'sports_basketball',
      tennis: 'sports_tennis',
      badminton: 'sports_tennis',
      golf: 'golf_course',
      swimming: 'pool',
      hiking: 'hiking',
      park: 'park',
      festival: 'festival',
      camera: 'camera_alt',
      headphones: 'headphones',
      radio: 'radio',
      toys: 'toys',
      garden: 'local_florist',
      camping: 'cabin',
      fishing: 'phishing',
    },
  },
  {
    label: 'Money & work',
    icons: {
      salary: 'payments',
      savings: 'savings',
      investment: 'trending_up',
      bonus: 'emoji_events',
      refund: 'undo',
      bank: 'account_balance',
      work: 'work',
      card: 'credit_card',
    },
  },
  {
    label: 'Tech & work',
    icons: {
      laptop: 'laptop',
      computer: 'computer',
      smartphone: 'smartphone',
      printer: 'print',
      cloud: 'cloud',
      software: 'terminal',
      office: 'business_center',
      badge: 'badge',
      engineering: 'engineering',
      meeting: 'handshake',
      freelance: 'laptop_mac',
    },
  },
  {
    label: 'Records & admin',
    icons: {
      insurance: 'shield',
      tax: 'account_balance_wallet',
      subscription: 'subscriptions',
      document: 'description',
      car_repair: 'car_repair',
      legal: 'gavel',
      policy: 'policy',
      verified: 'verified',
      licence: 'card_membership',
      passport: 'contact_page',
      key: 'key',
      lock: 'lock',
      folder: 'folder',
      insurance_car: 'directions_car',
    },
  },
  {
    label: 'Household items',
    icons: {
      box: 'inventory_2',
      bottle: 'local_drink',
      soap: 'soap',
      pest: 'pest_control',
      detergent: 'local_laundry_service',
      sanitizer: 'sanitizer',
      handwash: 'wash',
      cleaning_spray: 'cleaning_services',
      iron: 'iron',
      drycleaning: 'dry_cleaning',
      hanger: 'checkroom',
      fridge: 'kitchen',
      microwave: 'microwave',
      blender: 'blender',
      coffeemaker: 'coffee_maker',
      countertop: 'countertops',
      cutlery: 'flatware',
      cooking: 'soup_kitchen',
      sofa: 'weekend',
      table: 'table_restaurant',
      wardrobe: 'door_sliding',
      shelf: 'shelves',
      lamp: 'light',
      outlet: 'outlet',
      plug: 'electrical_services',
      battery: 'battery_full',
      propane: 'propane_tank',
      thermostat: 'thermostat',
      extinguisher: 'fire_extinguisher',
      firstaid: 'medical_services',
      umbrella: 'umbrella',
      hardware: 'hardware',
      handyman: 'handyman',
      toolbox: 'home_repair_service',
      crib: 'crib',
      stairs: 'stairs',
      garage: 'garage',
      balcony: 'balcony',
      deck: 'deck',
      fence: 'fence',
      bathroom: 'bathroom',
      bedroom: 'bedroom_parent',
      livingroom: 'living',
      diningroom: 'dining',
      curtains: 'curtains',
      grass: 'grass',
      plant: 'local_florist',
      waterdrop: 'water_drop',
      air: 'air',
      fireplace: 'fireplace',
    },
  },
  {
    label: 'Misc daily life',
    icons: {
      recycle: 'recycling',
      trash: 'delete',
      donation: 'redeem',
      religion: 'mosque',
      zakat: 'mosque',
      farming: 'agriculture',
      forest: 'forest',
      weather: 'wb_sunny',
      clock: 'schedule',
      calendar: 'calendar_month',
      location: 'place',
      language: 'translate',
      science: 'science',
      backpack: 'backpack',
      library: 'local_library',
    },
  },
  {
    label: 'Shapes',
    icons: {
      circle: 'circle',
      circle_outline: 'radio_button_unchecked',
      dot: 'fiber_manual_record',
      ring: 'trip_origin',
      square: 'square',
      square_outline: 'crop_square',
      rectangle: 'rectangle',
      triangle: 'change_history',
      pentagon: 'pentagon',
      hexagon: 'hexagon',
      diamond: 'diamond',
      heart_outline: 'favorite_border',
      star_outline: 'star_border',
      shield: 'shield',
      label_shape: 'label',
      grid: 'grid_view',
      blur: 'blur_on',
    },
  },
  {
    label: 'Symbols & colour',
    icons: {
      bolt: 'bolt',
      flame: 'local_fire_department',
      cloud_shape: 'cloud',
      sun: 'light_mode',
      moon: 'dark_mode',
      snow: 'ac_unit',
      palette: 'palette',
      colour_fill: 'format_color_fill',
      brush: 'brush',
      sparkle: 'auto_awesome',
      priority: 'priority_high',
      check: 'check_circle',
      warning: 'warning',
      info: 'info',
      block: 'block',
      pin: 'push_pin',
    },
  },
];

export const ICON_KEYS = Object.fromEntries(
  ICON_GROUPS.flatMap((g) => Object.entries(g.icons)),
);

/** Material ligature for a stored key; falls back the way the phone does. */
export function glyphFor(key) {
  return ICON_KEYS[String(key || '').toLowerCase()] || 'category';
}

export function isKnownIcon(key) {
  return Boolean(ICON_KEYS[String(key || '').toLowerCase()]);
}

/** An <span> rendering the icon for a stored key. */
export function iconEl(key, { size = 18, className = '' } = {}) {
  const node = document.createElement('span');
  node.className = `micon ${className}`.trim();
  node.textContent = glyphFor(key);
  node.style.fontSize = `${size}px`;
  return node;
}
